services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: productdb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d productdb -h localhost"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    build: .
    environment:
      DATABASE_URL: postgres://user:password@db:5432/productdb?sslmode=disable
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

